apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: unomi-hpa
  namespace: lulu-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: unomi-deploy
  minReplicas: 1
  maxReplicas: 50
  targetCPUUtilizationPercentage: 70