apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: yomoney-roles
  namespace: yomoney-poc-dev
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yomoney-role-bindings
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: yomoney-roles
subjects:
  - apiGroup: rbac.authorization.k8s.io
    name: f071caab-14be-433e-9711-32350418917f
    kind: Group
    namespace: yomoney-poc-dev
